### ISSUE TITLE
部署到windows服务器上，查询历史日志，弹出报错弹窗

### ISSUE THREAD

**Issue by highmind** [BetterJS/badjs-report#36]
{"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"} 

nodejs 控制台的错误：
 Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

**Comment by yorts52** [comment]
错误信息太少，无法判断具体原因，建议检查网络连通性及端口占用情况
